# Generated by Django 3.0.8 on 2020-10-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='latitude',
            field=models.CharField(max_length=30, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='longitude',
            field=models.CharField(max_length=30, verbose_name='longitude'),
        ),
        migrations.AlterUniqueTogether(
            name='bookings',
            unique_together={('date', 'slot')},
        ),
    ]
