# Generated by Django 3.0.8 on 2020-10-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='vehiclebrand',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='date'),
        ),
    ]
