# Generated by Django 3.0.8 on 2020-10-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20201012_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9, verbose_name='latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9, verbose_name='longitude'),
            preserve_default=False,
        ),
    ]
