# Generated by Django 3.0.8 on 2020-10-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20201012_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
