# Generated by Django 3.0.8 on 2020-09-02 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_phoneotp_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneotp',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
