# Generated by Django 3.0.8 on 2020-09-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_auto_20200902_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
