# Generated by Django 3.0.8 on 2020-09-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_phoneotp_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
